Header header

int32 arduinoMillis
int32 batteryMillivolts
int32 angleY
int32 angleX
int32 angleZ
int32 driveLeft
int32 driveRight
int32 speedLeft
int32 speedRight
int32 distanceLeft
int32 distanceRight
int32 IRsensor1 ## Added by group ##
int32 IRsensor2 ## Added by group ##
int32 IRsensor3 ## Added by group ##
int32 IRsensor4 ## Added by group ##
int32 IRsensor5 ## Added by group ##
int32 rangeSensor ## Added by group ##
